CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE public."Accounts" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(255) NULL,
    "LastName" character varying(255) NULL,
    "Username" character varying(255) NOT NULL,
    "PasswordHash" bytea NULL,
    "PasswordSalt" bytea NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201026010632_InitialCreate', '3.1.9');

